// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5f2c4Y1vBNEH6JL5KSkQ3EA1_IS5qSJY',
    appId: '1:764228186874:web:242f9d0d1bbcf976934f43',
    messagingSenderId: '764228186874',
    projectId: 'travello-103e2',
    authDomain: 'travello-103e2.firebaseapp.com',
    databaseURL: 'https://travello-103e2-default-rtdb.firebaseio.com',
    storageBucket: 'travello-103e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1YgR_L6XuV4EaHlAidMa_UeDof76EdhA',
    appId: '1:764228186874:android:d95c18353c7cbef3934f43',
    messagingSenderId: '764228186874',
    projectId: 'travello-103e2',
    databaseURL: 'https://travello-103e2-default-rtdb.firebaseio.com',
    storageBucket: 'travello-103e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApdylYjpsL7mY011hTwBk_L5uoHlnTrlQ',
    appId: '1:764228186874:ios:a85e9a590b4de249934f43',
    messagingSenderId: '764228186874',
    projectId: 'travello-103e2',
    databaseURL: 'https://travello-103e2-default-rtdb.firebaseio.com',
    storageBucket: 'travello-103e2.appspot.com',
    iosBundleId: 'com.example.travello',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApdylYjpsL7mY011hTwBk_L5uoHlnTrlQ',
    appId: '1:764228186874:ios:c2ad2581a9edbab5934f43',
    messagingSenderId: '764228186874',
    projectId: 'travello-103e2',
    databaseURL: 'https://travello-103e2-default-rtdb.firebaseio.com',
    storageBucket: 'travello-103e2.appspot.com',
    iosBundleId: 'com.example.travello.RunnerTests',
  );
}
